name: Continuous Integration

on:
  push:
    branches: [  main  ]

jobs:
  run_tests:
    runs-on: ubuntu-20.04 # ubuntu-latest wont work with 3.7.16
    strategy:
      fail-fast: false # if any set of tests fail, exit immediately. Doesn't give full error list
      matrix:
        python-version: [3.7.16, 3.8, 3.12.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;

    - name: Test with unittest
      run: |
        python -m unittest tests.test_root
