name: Continuous Integration

on:
  push:
    branches: [  main  ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # if any set of tests fail, exit immediately. Doesn't give full error list
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    # install python
    - name: Setup Python ${{ matrix.python-version }}
      uses: action/setup-python@v2
      with:
        python-version:${{ matrix.python-version }}

    # install python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;

    # run actual unit tests
    - name: Test with unittest
      run: |
        python -m unittest tests.test_root
